replicaCount: 2
fullnameOverride: "my-unique-identifier"
name: "awesomenodejs-app1"


image:
  repository: public.ecr.aws/c3w1m1q2
  tag: latest

resources:
  limits: 
    memory: 512Mi
    cpu: "1"
  requests:
    memory: 256Mi
    cpu: "0.2"

microservices:
  - name: microservice1
    port: 3000
  - name: microservice2
    port: 3001
  - name: microservice3
    port: 3002
  - name: microservice4
    port: 3003

services:
  name: "awesomenodejs-app1-service"
  port: 80
  targetPort: 3000